package com.rom4ster.musicmanagerreborn.utils

const val GRID_MIN_CELL_WIDTH = 384
const val CARD_PADDING_PLAYLISTS_HORIZONTAL = 20
const val CARD_PADDING_PLAYLISTS_VERTICAL = 10
const val CARD_SWIPE_WIDTH_PLAYLISTS_PERCENT = 0.5f
const val PLAYLISTS_GRID_INTERNAL_CARD_PADDING_HORIZONTAL = 10
const val PLAYLISTS_GRID_ADD_BUTTON_END_PADDING = 20
const val PLAYLISTS_GRID_ADD_BUTTON_BOTTOM_PADDING = 20
const val PLAYLIST_CARD_WIDTH = 0.8f